server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;

  location = / {
    try_files /frontend/html/gallary.html =404;
  }

  # I am not sure this is the best approach 

  # Bat
  location = /bat {
    try_files /frontend/html/editor.html =404;
  }
  location ~ ^/bat/.* {
    return 301 /bat;
  }

  # Sheep
  location = /sheep {
    try_files /frontend/html/editor.html =404;
  }
  location ~ ^/sheep/.* {
    return 301 /sheep;
  }

  # Dragon 1
  location = /horntail {
    try_files /frontend/html/editor.html =404;
  }
  location ~ ^/horntail/.* {
    return 301 /horntail;
  }

  # Dragon 2
  location = /dragon2 {
    try_files /frontend/html/editor.html =404;
  }
  location ~ ^/dragon2/.* {
    return 301 /dragon2;
  }

  location / {
    try_files $uri $uri/ =404;
  }

  location /assets/ {
    add_header Cache-Control "public, max-age=31536000, immutable";
    try_files $uri =404;
  }
}
